ARG centos=7
ARG image=php7-7.1

FROM aursu/pearbuild:${centos}-${image}

RUN yum -y --enablerepo=bintray-custom install \
        ImageMagick-devel \
    && yum clean all && rm -rf /var/cache/yum

COPY SOURCES ${BUILD_TOPDIR}/SOURCES
COPY SPECS ${BUILD_TOPDIR}/SPECS

RUN chown -R $BUILD_USER ${BUILD_TOPDIR}/{SOURCES,SPECS}

USER $BUILD_USER

ENTRYPOINT ["/usr/bin/rpmbuild", "php7-pecl-imagick.spec"]
CMD ["-ba"]
