version: "3.5"
services:
  centos7imagickphp81:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-8.1
  stream8imagickphp81:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.el8
      args:
        centos: $OS8
        image: php-8.1

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream
