version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.8

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  igbinarybuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7imagick
          build_service: centos7imagick
          bintray-repo: php74custom
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: stream8imagick
          build_service: stream8imagick
          bintray-repo: php74custom
          bintray_uploader: stream8bintray
      - docker-rpmbuild/build:
          name: centos7imagickphp81
          build_file: docker-compose.php81.yml
          build_service: centos7imagickphp81
          bintray-repo: php81custom
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: stream8imagickphp81
          build_file: docker-compose.php81.yml
          build_service: stream8imagickphp81
          bintray-repo: php81custom
          bintray_uploader: stream8bintray